# Основы линейной алгебры

## Работа с векторами и матрицами

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import random as rnd

In [19]:
base_list1 = [1, 2, 3, 4, 5]
base_list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 8]]

In [20]:
l = list(map(lambda n: 2 * n + 1, range(0, 10)))
l

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [21]:
rnd_l = list(map(lambda x: rnd.randrange(1, 100), range(0, 20)))
rnd_l

[12,
 73,
 47,
 11,
 41,
 95,
 27,
 37,
 38,
 88,
 45,
 22,
 41,
 75,
 91,
 75,
 50,
 45,
 48,
 56]

## NumPy

In [22]:
a = np.array([1, 2, 3])
A = np.array(base_list2)

print(a)
print(A)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 8]]


In [23]:
b = np.dot(A, a)
b

array([14, 32, 47])

In [24]:
c = np.cross(a, b)
d = np.dot(a, b)
c, d, a * b

(array([-2, -5,  4]), np.int64(219), array([ 14,  64, 141]))

In [25]:
def MatrixToVector(A, a):
    l = np.shape(A)
    b = [0] * l[0]
    for i in range(0, l[0]):
        s = 0
        for j in range(0, l[1]):
            s += A[i,j] * a[j]
        b[i] = s
    return np.array(b)

In [26]:
b1 = MatrixToVector(A, a)
b1

array([14, 32, 47])

In [27]:
def Transpose(A):
    l = np.shape(A)
    B = []
    for i in range(0, l[1]):
        b = []
        for j in range(0, l[0]):
            b.append(A[j, i])
        B.append(b)
    return np.array(B)

C = Transpose(A)
D = A.transpose()
D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 8]])

In [28]:
C = [[0]*5]*7
C

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [29]:
def MatrixToMatrix(A, B):
    la = np.shape(A)
    lb = np.shape(B)

    C = []
    for i in range(0, lb[1]):
        C.append([0]*la[0])

    for i in range(0, la[0]):
        for j in range(0, lb[1]):
            s = 0
            for k in range(0, la[1]):
                s += A[i, k] * B[k, j]
            C[i][j] = s

    return np.array(C)

C = MatrixToMatrix(A, A.transpose())
C

array([[ 14,  32,  47],
       [ 32,  77, 116],
       [ 47, 116, 177]])

In [53]:
def Triangle(A):
    def Swap(M, r1, r2):
        if r1 == r2: return False
        m = np.shape(M)[1]
        for j in range(0, m):
            M[r1, j], M[r2, j] = M[r2, j], M[r1, j]
        return True

    M = np.array(A, dtype='d')
    n, m = np.shape(M)
    d = 1.0
    rank = min(n, m)

    for i0 in range(0, rank):
        if(M[i0, i0] == 0):
            max = 0.0
            max_i = -1

            for i1 in range(i0 + 1, n):
                abs_a = abs(M[i1, i0])
                if abs_a > max:
                    max, max_i = abs_a, i1
            
            if max_i < 0:
                for i in range(i0, n):
                    for j in range(i0, m):
                        M[i, j] = 0.0
            
            if Swap(M, i0, max_i):
                d = -d

        pivot = M[i0, i0]
        d *= pivot

        for i in range(i0 + 1, n):
            if M[i, i0] != 0:
                k = float(M[i, i0]) / pivot
                M[i, i0] = 0.0
                for j in range(i0 + 1, m):
                    M[i, j] -= float(M[i0, j]) * k

    return M, rank, d

T, r, d = Triangle(A)
T, r, d

(array([[ 1.,  2.,  3.],
        [ 0., -3., -6.],
        [ 0.,  0., -1.]]),
 3,
 np.float64(3.0))

In [40]:
TT = np.triu(A)
A, TT

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 8]]),
 array([[1, 2, 3],
        [0, 5, 6],
        [0, 0, 8]]))