# Основы линейной алгебры

## Работа с векторами и матрицами

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random as rnd
import scipy.linalg as lp

In [2]:
base_list1 = [1, 2, 3, 4, 5]
base_list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 8]]

In [3]:
l = list(map(lambda n: 2 * n + 1, range(0, 10)))
l

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [4]:
rnd_l = list(map(lambda x: rnd.randrange(1, 100), range(0, 20)))
rnd_l

[4, 71, 69, 17, 14, 63, 50, 65, 24, 14, 93, 77, 14, 87, 87, 27, 55, 92, 83, 3]

## NumPy

In [5]:
a = np.array([1, 2, 3])
A = np.array(base_list2)

print(a)
print(A)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 8]]


In [6]:
b = np.dot(A, a)
b

array([14, 32, 47])

In [7]:
c = np.cross(a, b)
d = np.dot(a, b)
c, d, a * b

(array([-2, -5,  4]), np.int64(219), array([ 14,  64, 141]))

In [8]:
def MatrixToVector(A, a):
    l = np.shape(A)
    b = [0] * l[0]
    for i in range(0, l[0]):
        s = 0
        for j in range(0, l[1]):
            s += A[i,j] * a[j]
        b[i] = s
    return np.array(b)

In [9]:
b1 = MatrixToVector(A, a)
b1

array([14, 32, 47])

In [10]:
def Transpose(A):
    l = np.shape(A)
    B = []
    for i in range(0, l[1]):
        b = []
        for j in range(0, l[0]):
            b.append(A[j, i])
        B.append(b)
    return np.array(B)

C = Transpose(A)
D = A.T
D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 8]])

In [11]:
C = [[0]*5]*7
C

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [12]:
def MatrixToMatrix(A, B):
    la = np.shape(A)
    lb = np.shape(B)

    C = []
    for i in range(0, lb[1]):
        C.append([0]*la[0])

    for i in range(0, la[0]):
        for j in range(0, lb[1]):
            s = 0
            for k in range(0, la[1]):
                s += A[i, k] * B[k, j]
            C[i][j] = s

    return np.array(C)

C = MatrixToMatrix(A, A.transpose())
C

array([[ 14,  32,  47],
       [ 32,  77, 116],
       [ 47, 116, 177]])

In [41]:
def Triangle(A):
    # Добавляем локальный метод обмена строк местами
    def Swap(M, r1, r2):
        if r1 == r2: return False # если индексы совпадают, то ничего не делаем
        m = np.shape(M)[1]
        for j in range(0, m):
            M[r1, j], M[r2, j] = M[r2, j], M[r1, j]
        return True

    # делаем копию входного массива что бы не портить его
    M = np.array(A, dtype='d') # и насильно устанавливаем тип данных ячеек
    n, m = np.shape(M)
    d = 1.0 # определитель матрицы будет мультипликативно меняться
    rank = min(n, m)
    P = np.eye(rank) # единичная матрица, которая будет превращена в матрицу пермутаций

    # бежим по строкам/столбцам (диагонали) матрицы
    for i0 in range(0, rank):
        if(M[i0, i0] == 0):
            # если очередной элемент 0, то строку надо менять со строкой, 
            # в которой первый элемент дложен быть максимальным (ХЗ почему...)
            max = 0.0
            max_i = -1 # тут нам нужен будет индекс строки с максимальным элементом

            for i1 in range(i0 + 1, n): # ищем максимальный элемент в столбце ниже
                abs_a = abs(M[i1, i0])
                if abs_a > max:
                    max, max_i = abs_a, i1 # нашли максимум, запоминаем индекс строки
            
            if max_i < 0: # если не был найден ни один элемент больше 0
                for i in range(i0, n): # обнуляем стобец
                    for j in range(i0, m):
                        M[i, j] = 0.0
            
            if Swap(M, i0, max_i): # если найден элемент
                d = -d # при перестановке строк определитель меняет знак
                Swap(P, i0, max_i) # изменяем матрицу перестановок

        pivot = M[i0, i0] # текущий элемент диагонали - опорный
        d *= pivot # сразу расчитываем определитель

        for i in range(i0 + 1, n): # для всех строк ниже текущей
            if M[i, i0] != 0: # если элемент не 0, то нужно удалять строку (обнулять элемент)
                k = float(M[i, i0]) # pivot # расчитываем коэффициент для всех элементов строки
                M[i, i0] = 0.0 # тупо обнуляем элемент без математики
                for j in range(i0 + 1, m): # а для всех остальных элементов в строке
                    M[i, j] -= float(M[i0, j]) * k # вычитаем опорную строку из текущей

    # возвращаем треугольную матрицу, ранг, определитель и матрицу перестановок
    return M, rank, d, P

T, r, d, P = Triangle(A)
T, r, d, P

(array([[  1.,   2.,   3.],
        [  0.,  -3.,  -6.],
        [  0.,   0., -49.]]),
 3,
 np.float64(147.0),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [45]:
def Reverse(A):
    # Добавляем локальный метод обмена строк местами
    def Swap(M, r1, r2):
        if r1 == r2: return False
        m = np.shape(M)[1]
        for j in range(0, m):
            M[r1, j], M[r2, j] = M[r2, j], M[r1, j]
        return True

    M = np.array(A, dtype='d')
    size = np.shape(M)
    n, m = size
    d = 1.0
    rank = min(n, m)
    E = np.eye(rank) # здесь будет сйормирована обратная матрица. В начале это единичная матрица.
    P = np.eye(rank)

    # Сперва прямой ход метода - приведение исходной матрицы к треугольному виду совместно с единичной матрицей
    for i0 in range(0, rank):
        if(M[i0, i0] == 0):
            max = 0.0
            max_i = -1

            for i1 in range(i0 + 1, n):
                abs_a = abs(M[i1, i0])
                if abs_a > max:
                    max, max_i = abs_a, i1
            
            if max_i < 0:
                for i in range(i0, n):
                    for j in range(i0, m):
                        M[i, j] = 0.0
            
            if Swap(M, i0, max_i):
                d = -d
                Swap(E, i0, max_i)
                Swap(P, i0, max_i)

        pivot = M[i0, i0]
        d *= pivot

        for i in range(i0 + 1, n):
            if M[i, i0] != 0:
                k = M[i, i0] / pivot
                M[i, i0] = 0.0

                for j in range(i0 + 1, m):
                    M[i, j] -= M[i0, j] * k
                # Дополнительно применяем то же преобразование ко вссей строке единичной матрицы
                for j in range(0, m):
                    E[i, j] -= E[i0, j] * k

    # Теперь аналогичными методами надо обнулить верхний треугольник матрицы M
    for i0 in range(rank - 1, -1, -1): 
        # идём в обратном направлении снизу вверх по строкам
        # i0 - номер строки от последней вверх (она же - номер столбца)
        pivot = M[i0, i0] # диагональный элемент триугольной матрицы

        if pivot != 1: # если имеет смысл нормировать
            for j in range(0, m): # строку нормируем по элементу строки триугольной матрицы
                E[i0, j] /= pivot

        # для всех строк выше текущей
        for i in range(i0 - 1, -1, -1): 
            k = M[i, i0]
            if(k != 0):
                M[i, i0] = 0
                for j in range(0, m):
                    E[i, j] -= E[i0, j] * k

    # Возвращаем обратную матрицу (Е), матрицу перестановок, определитель матрицы A, диагональную матрицу (в диагонали ХЗ что)
    return E, P, d, M

invA, P, d, M = Reverse(A)
invA, A @ invA, M, d

(array([[-2.66666667,  2.66666667, -1.        ],
        [ 3.33333333, -4.33333333,  2.        ],
        [-1.        ,  2.        , -1.        ]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 1.,  0.,  0.],
        [ 0., -3.,  0.],
        [ 0.,  0., -1.]]),
 np.float64(3.0))