# Основы линейной алгебры

## Работа с векторами и матрицами

In [7]:
import numpy as np
import matplotlib.pyplot as plt
import random as rnd

In [14]:
base_list1 = [1, 2, 3, 4, 5]
base_list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [2]:
l = list(map(lambda n: 2 * n + 1, range(0, 10)))
l

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [12]:
rnd_l = list(map(lambda x: rnd.randrange(1, 100), range(0, 20)))
rnd_l

[69, 3, 69, 91, 48, 7, 9, 94, 37, 93, 50, 62, 88, 42, 44, 43, 46, 23, 46, 10]

## NumPy

In [17]:
a = np.array([1, 2, 3])
A = np.array(base_list2)

print(a)
print(A)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
b = np.dot(A, a)
b

array([14, 32, 50])

In [26]:
c = np.cross(a, b)
d = np.dot(a, b)
c, d, a * b

(array([ 4, -8,  4]), np.int64(228), array([ 14,  64, 150]))

In [43]:
def MatrixToVector(A, a):
    l = np.shape(A)
    b = [0] * l[0]
    for i in range(0, l[0]):
        s = 0
        for j in range(0, l[1]):
            s += A[i,j] * a[j]
        b[i] = s
    return np.array(b)

In [44]:
b1 = MatrixToVector(A, a)
b1

array([14, 32, 50])

In [49]:
def Transpose(A):
    l = np.shape(A)
    B = []
    for i in range(0, l[1]):
        b = []
        for j in range(0, l[0]):
            b.append(A[j, i])
        B.append(b)
    return np.array(B)

C = Transpose(A)
D = A.transpose()
D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [50]:
C = [[0]*5]*7
C

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [71]:
def MatrixToMatrix(A, B):
    la = np.shape(A)
    lb = np.shape(B)

    C = []
    for i in range(0, lb[1]):
        C.append([0]*la[0])

    for i in range(0, la[0]):
        for j in range(0, lb[1]):
            s = 0
            for k in range(0, la[1]):
                s += A[i, k] * B[k, j]
            C[i][j] = s

    return np.array(C)

C = MatrixToMatrix(A, A.transpose())
C

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])